### ISSUE TITLE
iTol.py: No warning given if mapping file sample IDs are not in the BIOM table

### ISSUE THREAD

**Issue by smdabdoub** [smdabdoub/phylotoast#27]
When calculating raw abundance (for example), if there is no overlap in sample IDs between the mapping file and the BIOM table, the output will be zero for each OTU.

While the mapping file is not strictly necessary for calculating raw abundance, it is for the other calculations. As such it is a required argument to the program. Additionally, for greater code simplicity the abundance calculation methods in the biom_calc module take a list of sample IDs. In the case of iTol.py calculating total OTU abundance, it just passes all the sample IDs in the mapping file to the abundance calculation methods. If none of those sample IDs are found in the BIOM table, nothing will be calculated and all zeroes will be output.

For these reasons, changing the code to just for the raw abundance use case would add unnecessary complexity. Instead, a warning should be output if no overlap in sample IDs is found between the mapping file and the BIOM table.

**Comment by akshayparopkari** [comment]
iTol updated their dataset file formats. [Here](http://itol.embl.de/help.cgi#datasets) is more information about the change.

**Comment by akshayparopkari** [comment]
Fixed dataset format output in PR #31.
