### ISSUE TITLE
phylotoast is not in PyPI

### ISSUE THREAD

**Issue by mthon** [smdabdoub/phylotoast#29]
The docs say that phylotoast in in pypi but the command `pip install phylotoast` fails. A search of the pypi.org website also fails to locate the package.

**Comment by smdabdoub** [comment]
You are correct, apologies. The project name was changed a while back, and we have yet to update pypi with the new name. I will start working on that, and hopefully have something up by today or tomorrow. Thank you for the reminder

**Comment by druvus** [comment]
Any updates on the progress of this issue?

**Comment by smdabdoub** [comment]
Yes, we have been making some additions and changes, but the new version will be out on pypi later today.

**Comment by smdabdoub** [comment]
PhyloToAST v1.3.0 is now available on PyPI:

https://pypi.python.org/pypi/phylotoast/1.3.0

**Comment by druvus** [comment]
thanks, I have added a bioconda recipe based on the PyPI version.
