### ISSUE TITLE
Update PCoA_bubble

### ISSUE THREAD

**Issue by smdabdoub** [smdabdoub/phylotoast#42]
The PCoA_bubble script was written very early on, and never updated along with the rest of the visualization scripts. The code needs to be cleaned up in general, but a few specific things need to be addressed:

- Remove dependence on the custom file format for specifying group names (mapping file column), colors (colors column in the mapping file), and OTU names (which can now be automatically generated by the otu_calc module)
- Use the relative abundance method now available in the biom_calc module
- Replace link_samples_to_categories() with the gather_categories method in the util module
- Make applying the ggplot2 style optional

**Comment by akshayparopkari** [comment]
Addressed all bullet points in #46
