### ISSUE TITLE
How to remove/move legend in PCoA plots

### ISSUE THREAD

**Issue by kali1819** [smdabdoub/phylotoast#69]
Hello, 

Is there any option to move or remove legend while making PCoA plots? My legend box is inside the plot and it is covering some plot points.

**Comment by smdabdoub** [comment]
Hi @kali1819 ,

Thanks for the question. I've updated PCoA.py to allow selection of legend placement options (including outside the plot frame) as well as no legend. Let me know if you have any issues!
